[s6_switches]
spine_m ansible_host=10.206.60.1
spine_b ansible_host=10.206.60.2
leaf1_m ansible_host=10.206.60.3
leaf1_b ansible_host=10.206.60.4
leaf2_m ansible_host=10.206.60.5
leaf2_b ansible_host=10.206.60.6
#leaf3_m ansible_host=10.206.60.7
#leaf3_b ansible_host=10.206.60.8

[s6_switches:vars]
ansible_user=admin
ansible_password=Video@123
ansible_network_os=cisco.nxos.nxos
ansible_connection=network_cli